# Generated by Django 2.0.4 on 2018-08-16 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationConge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_damande', models.DateField()),
                ('date_sortie_conge', models.DateField()),
                ('date_entre_conge', models.DateField()),
                ('nbr_jours', models.IntegerField(default=0)),
                ('avis_admin', models.CharField(max_length=250)),
                ('etat_conge', models.CharField(max_length=200)),
                ('commentaire_conge', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('cin', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('tel', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=250)),
                ('solde_conge', models.IntegerField(default=26)),
            ],
        ),
        migrations.CreateModel(
            name='ManageConge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conge_manage_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congemanagement.Conge')),
            ],
        ),
        migrations.CreateModel(
            name='ManageEmploye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employe_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congemanagement.Employe')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField(choices=[(0, ''), (1, 'Agent standard'), (2, 'Responsable RH'), (4, 'President')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='manageemploye',
            name='user_profile_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congemanagement.UserProfile'),
        ),
        migrations.AddField(
            model_name='manageconge',
            name='manager_conge_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congemanagement.UserProfile'),
        ),
        migrations.AddField(
            model_name='employe',
            name='user_manage_employe',
            field=models.ManyToManyField(through='congemanagement.ManageEmploye', to='congemanagement.UserProfile'),
        ),
        migrations.AddField(
            model_name='conge',
            name='employe_to_conge',
            field=models.ManyToManyField(through='congemanagement.ApplicationConge', to='congemanagement.Employe'),
        ),
        migrations.AddField(
            model_name='conge',
            name='user_manage_conge',
            field=models.ManyToManyField(through='congemanagement.ManageConge', to='congemanagement.UserProfile'),
        ),
        migrations.AddField(
            model_name='applicationconge',
            name='conge_app_application_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congemanagement.Conge'),
        ),
        migrations.AddField(
            model_name='applicationconge',
            name='employe_application_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congemanagement.Employe'),
        ),
    ]
