# Generated by Django 2.0.4 on 2018-08-16 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congemanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CongeClasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateField()),
                ('date_sortie_conge', models.DateField()),
                ('date_entre_conge', models.DateField()),
                ('nbr_jour', models.IntegerField(default=0)),
                ('avis_admin', models.CharField(max_length=250)),
                ('etat_conge', models.CharField(max_length=100)),
                ('commentaire_conge', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='conge',
            name='employe_to_conge',
        ),
        migrations.RemoveField(
            model_name='conge',
            name='user_manage_conge',
        ),
        migrations.AlterField(
            model_name='applicationconge',
            name='conge_app_application_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congemanagement.CongeClasse'),
        ),
        migrations.AlterField(
            model_name='manageconge',
            name='conge_manage_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congemanagement.CongeClasse'),
        ),
        migrations.DeleteModel(
            name='Conge',
        ),
        migrations.AddField(
            model_name='congeclasse',
            name='emp_has_conge',
            field=models.ManyToManyField(through='congemanagement.ApplicationConge', to='congemanagement.Employe'),
        ),
        migrations.AddField(
            model_name='congeclasse',
            name='user_manager',
            field=models.ManyToManyField(through='congemanagement.ManageConge', to='congemanagement.UserProfile'),
        ),
    ]
