# Generated by Django 2.0.4 on 2018-08-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congemanagement', '0005_auto_20180820_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='avis_admin',
            field=models.CharField(default='En attente', max_length=250),
        ),
        migrations.AlterField(
            model_name='conge',
            name='etat_conge',
            field=models.CharField(default='En attente', max_length=100),
        ),
    ]
