# Generated by Django 2.0.4 on 2018-08-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congemanagement', '0006_auto_20180820_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='commentaire_conge',
            field=models.CharField(default='Pas encore', max_length=250),
        ),
    ]
