# Generated by Django 2.0.4 on 2018-08-25 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congemanagement', '0007_auto_20180820_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manageemploye',
            name='employe_FK',
        ),
        migrations.RemoveField(
            model_name='manageemploye',
            name='user_profile_FK',
        ),
        migrations.AlterModelOptions(
            name='conge',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='employe',
            name='user_manage_employe',
        ),
        migrations.AddField(
            model_name='employe',
            name='user_manage_employe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='congemanagement.UserProfile'),
        ),
        migrations.DeleteModel(
            name='ManageEmploye',
        ),
    ]
