# Generated by Django 2.0.4 on 2018-08-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congemanagement', '0008_auto_20180825_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisableDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, null=True)),
                ('date_disable', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RangeDisableDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('date_begin', models.DateField()),
                ('date_out', models.DateField()),
                ('nbr_days', models.IntegerField(default=0)),
            ],
        ),
    ]
